In [3]:
import numpy as np
arr1=np.arange(100).reshape(10,10)
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [9]:
np.save(r'C:\Users\nswdwy_yu\Desktop\ceshizhong',arr1)   #保存单个数组

In [10]:
arr2=np.random.randint(10,100,size=(10,10))
print(arr2)

[[31 15 60 58 40 23 15 32 90 63]
 [50 31 60 42 37 91 47 36 66 42]
 [11 52 96 85 46 25 27 31 23 66]
 [77 79 99 79 45 64 30 32 58 91]
 [66 30 70 32 94 48 88 25 27 62]
 [45 66 20 38 20 39 14 31 51 63]
 [21 31 29 44 70 54 53 40 65 60]
 [30 35 62 40 44 81 34 33 51 32]
 [75 93 88 84 78 49 52 58 30 91]
 [39 67 84 50 99 41 49 39 33 95]]


In [12]:
np.savez(r'C:\Users\nswdwy_yu\Desktop\ceshizhong',arr1,arr2) #保存多个数组

In [14]:
load_data=np.load(r'C:\Users\nswdwy_yu\Desktop\ceshizhong.npz')
print(load_data['arr_0'])   #读取

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [16]:
load_data_npy=np.load(r'C:\Users\nswdwy_yu\Desktop\ceshizhong.npy')
print(load_data_npy)   #读取.npy

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [20]:
np.savetxt(r'C:\Users\nswdwy_yu\Desktop\save_text1',arr1,fmt='%d',
           delimiter=',')

In [23]:
load_arr2=np.loadtxt(r'C:\Users\nswdwy_yu\Desktop\save_text1',
                        delimiter=',',dtype=np.int32)
print(load_arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [26]:
load_arr3=np.genfromtxt(r'C:\Users\nswdwy_yu\Desktop\save_text1',
                           delimiter=',', dtype=np.int32)
print(load_arr3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
