In [2]:
import numpy as np

In [14]:
arr1=np.arange(1,11,2)
print(arr1)

[1 3 5 7 9]


In [7]:
df=np.dtype([('name',np.str_,20),('age',np.int32),('score',np.float32)])
arr2=np.array([('曹贼',32,89),('刘备',25,90),('孙权',22,95)])
print(arr2)

[['曹贼' '32' '89']
 ['刘备' '25' '90']
 ['孙权' '22' '95']]


In [34]:
print(arr2[1:3,0:3])

[['刘备' '25' '90']
 ['孙权' '22' '95']]


In [76]:
arr3=np.arange(1,13,1)
arr4=arr3.reshape(3,4)  #变换数组的形态
print(arr3)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [73]:
arr=arr4.reshape(12)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [75]:
print(arr.flatten())   #横向展平
print(arr.flatten('f'))#纵向展平
print(arr.ravel())     #横向展平


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
arr_junyun=np.random.rand(5,7)  #5行7列的均匀分布
print(arr_junyun)

[[0.9137592  0.73047642 0.66942818 0.82647955 0.56703084 0.28014963
  0.04777882]
 [0.56090412 0.34361872 0.78218001 0.37940802 0.82626156 0.54731553
  0.75408239]
 [0.48541787 0.92621993 0.93863365 0.03998346 0.91697153 0.87747988
  0.63755209]
 [0.5786301  0.37152559 0.26922277 0.70914707 0.82439667 0.52713525
  0.54385645]
 [0.89182745 0.31152268 0.67402029 0.90942448 0.05753531 0.71760026
  0.01016759]]


In [5]:
arr_zhengtai=np.random.randn(7,5)  #7行5列正态分布的数
print(arr_zhengtai)

[[-0.84649922 -0.02286334  0.99309074  1.0156706   0.11025779]
 [-0.85560288 -1.02167408 -0.40609214  0.3726773   0.50035923]
 [ 1.14650118  0.18253669  0.62906919 -0.45312585  0.16911896]
 [-0.79188623  0.95303179 -0.33848631  0.55688072 -0.20298116]
 [-0.7942405   0.27706825 -1.34302973 -0.40923553  0.63480992]
 [-0.58462034  1.03357328 -0.22828062  1.75442036 -0.42653593]
 [-0.04465644 -0.74456354  0.61425748  0.10946107  0.13665844]]


In [ ]:
arr5=