In [9]:
import numpy as np
np.random.seed(34)    ###seed生成随机种子
arr1=np.random.randint(10,40,size=10)
print(arr1)

[11 36 20 19 32 31 14 13 15 21]


In [11]:
arr1.sort()
print(arr1)

[11 13 14 15 19 20 21 31 32 36]


In [18]:
arr2=np.random.randint(10,40,size=(4,5))
print(arr2)

[[18 18 25 20 23]
 [30 18 20 23 14]
 [12 15 12 36 20]
 [21 12 19 36 16]]


In [24]:
arr2.sort(axis=0)
print(arr2)

[[12 12 12 20 14]
 [18 15 19 23 16]
 [21 18 20 36 20]
 [30 18 25 36 23]]


In [25]:
arr3=np.array([2,5,10,4,8])
print(arr3)

[ 2  5 10  4  8]


In [26]:
print(arr3.argsort())

[0 3 1 4 2]


In [32]:
a=np.array([3,2,4])
b=np.array([4,10,3])
c=np.array([2,18,5])
d=np.lexsort((a,b,c))
print(list(zip(a[d],b[d],c[d])))

[(3, 4, 2), (4, 3, 5), (2, 10, 18)]


In [33]:
arr_random=np.random.randint(10,40,size=(4,5))
print(arr_random)

[[34 12 16 20 10]
 [21 31 30 26 30]
 [14 35 33 30 36]
 [35 23 22 33 29]]


In [35]:
print(np.sum(arr_random))   #求所以数组元素的和

520


In [36]:
##axis=1  列   axis=0  行
print(arr_random.sum(axis=1))   #求每一列的和  

[ 92 138 148 142]


In [38]:
print(arr_random.sum(axis=0))   #求每一行的和

[104 101 101 109 105]


In [39]:
print(arr_random.std(axis=1))   #求每一列的标准差

[8.5229103  3.72021505 8.06473806 5.2       ]


In [40]:
print(arr_random.var(axis=1))   #求每一列的方差

[72.64 13.84 65.04 27.04]


In [41]:
print(arr_random.mean(axis=1))   #求每一列的均值

[18.4 27.6 29.6 28.4]


In [42]:
arr4=np.arange(1,5,1)
print(arr4)

[1 2 3 4]


In [43]:
print(np.cumsum(arr4))   #不聚类加法

[ 1  3  6 10]


In [45]:
print(np.cumprod(arr4))   #不聚类乘法

[ 1  2  6 24]
