In [1]:
import numpy as np
arr1=np.random.randint(10.50,size=(4,3))
print(arr1)

[[0 9 1]
 [9 3 4]
 [8 6 3]
 [4 1 3]]


In [2]:
arr2=np.random.randint(1,10,size=(4,3))
print(arr2)

[[7 3 7]
 [3 6 4]
 [4 6 1]
 [6 1 6]]


In [4]:
arr2.flatten()

array([7, 3, 7, 3, 6, 4, 4, 6, 1, 6, 1, 6])

In [5]:
arr2.flatten('f')

array([7, 3, 4, 6, 3, 6, 6, 1, 7, 4, 1, 6])

In [7]:
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[0 9 1 7 3 7]
 [9 3 4 3 6 4]
 [8 6 3 4 6 1]
 [4 1 3 6 1 6]]


In [8]:
arr4=np.concatenate((arr1,arr2),axis=0)
print(arr4)

[[0 9 1]
 [9 3 4]
 [8 6 3]
 [4 1 3]
 [7 3 7]
 [3 6 4]
 [4 6 1]
 [6 1 6]]


In [15]:
print(arr3)
np.split(arr3,2,axis=1)
print(arr3[:,1:5])

[[0 9 1 7 3 7]
 [9 3 4 3 6 4]
 [8 6 3 4 6 1]
 [4 1 3 6 1 6]]
[[9 1 7 3]
 [3 4 3 6]
 [6 3 4 6]
 [1 3 6 1]]


In [25]:
import random

list = [20, 16, 10, 5]
random.shuffle(list)
print ("随机排序列表 : ",  list)

random.shuffle(list)
print ("随机排序列表 : ",  list)

随机排序列表 :  [16, 10, 20, 5]
随机排序列表 :  [20, 5, 16, 10]
