In [10]:
import numpy as np

In [11]:
mat1=np.mat('1,2,3;4,5,6')
print(mat1)

[[1 2 3]
 [4 5 6]]


In [13]:
mat2=np.mat([[3,2,1],[1,2,3]])
print(mat2)

[[3 2 1]
 [1 2 3]]


In [15]:
mat3=np.bmat('mat1,mat2;mat1,mat2')
print(mat3)

[[1 2 3 3 2 1]
 [4 5 6 1 2 3]
 [1 2 3 3 2 1]
 [4 5 6 1 2 3]]


In [42]:
mat11=np.mat('1,2;3,4;5,6')
print(mat11)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
print(mat1*mat11)

[[22 28]
 [49 64]]


In [16]:
print(mat1+1)

[[2 3 4]
 [5 6 7]]


In [18]:
print(mat2*2)

[[6 4 2]
 [2 4 6]]


In [38]:
print(mat2.T[:2,1])

[[1]
 [2]]


In [36]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1>arr2)
print(arr1+arr2)

[False False False]
[5 7 9]
