In [19]:
import numpy as np           #导入numpy库
arr1=np.array([1,2,3,4])
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
arr2=np.array([(1,2,3,4),(3,4,5,6)])
print(arr2)

[[1 2 3 4]
 [3 4 5 6]]


In [8]:
print(arr2.ndim)   #维度

2


In [9]:
print(arr2.shape)  #几行几列

(2, 4)


In [10]:
print(arr2.size)   #元素总个数

8


In [11]:
print(arr2.dtype)   #元素类型


int32


In [12]:
print(arr2.itemsize)  

4


In [17]:
arr3=np.arange(1,10,1)   #np.array(开始值，结束值，步长)   不包括结束值
print(arr3)
print(arr3.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [18]:
arr3.shape=(3,3)   #改变维度
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
arr4=np.linspace(1,10,5)    #np.linspqce(开始，结束，元素个数)  包括结束值
print(arr4)

[ 1.    3.25  5.5   7.75 10.  ]


In [31]:
arr5=np.logspace(1,4,8)     #np.logspace(开始幂次，结束幂次，元素个数)
print(arr5)

[   10.            26.82695795    71.9685673    193.06977289
   517.94746792  1389.49549437  3727.59372031 10000.        ]


In [32]:
arr_zeros=np.zeros((3,2))   #产生一个 0 矩阵
print(arr_zeros)         

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [37]:
arr_eye=np.eye(3,3)   #产生单位矩阵(主对角线为 1 )
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
arr_ones=np.ones((3,3)) #产生一个全 1 矩阵
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
arr_diag=np.diag([1,2,3,4])  #产生主对角线是所输入的集合的矩阵
print(arr_diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [45]:
arr6=np.eye(3,3)
print(arr6.dtype)

float64


In [48]:
arr6.dtype=np.int64
print(arr6)

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]


In [62]:
df=np.dtype([('name',np.str_,20),('age',np.int32),('score',np.float32)])
arr7=np.array([('曹贼',32,89),('刘备',25,90),('孙权',22,95)],
              dtype=df)
print(arr7)

[('曹贼', 32, 89.) ('刘备', 25, 90.) ('孙权', 22, 95.)]


In [69]:
arr8=np.random.rand(6)   #np.random.random(n) 随机产生n个0~1之间的数
print(arr8)

[0.62723613 0.76234293 0.40327782 0.48295478 0.85925833 0.36359785]


In [70]:
arr9=np.random.randint(1,10,size=(8,))
print(arr9)

[5 7 7 3 3 2 9 3]


In [73]:
arr10=np.permutation(arr9)
print(arr10)

AttributeError: module 'numpy' has no attribute 'permutation'